import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { Heart, MessageSquare, Plus, Send, Share2, X } from 'lucide-react';

export const CommunityPage: React.FC = () => {
  const { user, posts, addPost, toggleLikePost } = useAuth();
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [showNewPostModal, setShowNewPostModal] = useState(false);
  const [postTitle, setPostTitle] = useState('');
  const [postContent, setPostContent] = useState('');
  const [postCategory, setPostCategory] = useState<'Build in Public' | 'Questions' | 'Projects' | 'Hackathons' | 'AI' | 'Android' | 'General'>('Build in Public');
  const categories = ['All', 'Build in Public', 'Questions', 'Projects', 'Hackathons', 'AI', 'Android'];
  const filteredPosts = selectedCategory === 'All' ? posts : posts.filter((post) => post.category === selectedCategory);

  const handleCreatePost = (event: React.FormEvent) => {
    event.preventDefault();
    if (!postContent.trim() || !user) return;
    addPost({ authorName: user.name, authorCollege: user.college, authorAvatar: user.avatar, authorRole: user.role, authorRep: user.rep, category: postCategory, title: postTitle.trim() || undefined, content: postContent.trim() });
    setPostTitle(''); setPostContent(''); setShowNewPostModal(false);
  };

  return <div className="space-y-8 pb-16">
    <section className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b-2 border-outline-variant pb-7"><div><p className="font-label-mono text-[10px] uppercase tracking-[0.18em] text-on-surface-variant">COMMUNITY / LIVE DATA</p><h2 className="dc-display text-5xl sm:text-6xl mt-2">COMMUNITY.</h2><p className="mt-4 text-sm text-on-surface-variant max-w-xl">Posts are created by real DevCollective users. Nothing is pre-seeded.</p></div><button onClick={() => setShowNewPostModal(true)} className="px-5 py-3 bg-primary text-on-primary border-2 border-outline-variant shadow-[4px_4px_0_#171717] font-label-mono text-[10px] uppercase font-bold flex items-center gap-2"><Plus className="w-4 h-4" /> New Post</button></section>
    <div className="flex flex-wrap gap-2">{categories.map((category) => <button key={category} onClick={() => setSelectedCategory(category)} className={`px-3 py-2 border-2 border-outline-variant font-label-mono text-[10px] uppercase font-bold ${selectedCategory === category ? 'bg-primary text-on-primary shadow-[3px_3px_0_#171717]' : 'bg-surface'}`}>{category}</button>)}</div>
    <section className="space-y-5"><p className="font-label-mono text-[10px] uppercase text-on-surface-variant">{selectedCategory} / {filteredPosts.length} POSTS</p>{filteredPosts.length === 0 ? <div className="border-2 border-dashed border-outline-variant bg-surface p-12 text-center"><MessageSquare className="w-7 h-7 mx-auto mb-4 text-primary" /><h3 className="dc-display text-3xl">NO POSTS YET.</h3><p className="text-sm text-on-surface-variant mt-3">Be the first real member to publish something here.</p><button onClick={() => setShowNewPostModal(true)} className="mt-5 border-2 border-outline-variant bg-dc-mint px-4 py-3 font-label-mono text-[10px] uppercase font-bold">CREATE FIRST POST</button></div> : filteredPosts.map((post) => <article key={post.id} className="border-2 border-outline-variant bg-surface p-6 shadow-[4px_4px_0_#171717]"><div className="flex items-center justify-between gap-4 mb-4"><div className="flex items-center gap-3">{post.authorAvatar ? <img src={post.authorAvatar} alt={post.authorName} className="w-11 h-11 border-2 border-outline-variant object-cover" /> : <div className="w-11 h-11 border-2 border-outline-variant bg-dc-yellow flex items-center justify-center font-bold">{post.authorName.slice(0,1)}</div>}<div><h4 className="font-bold">{post.authorName}</h4><p className="font-label-mono text-[9px] uppercase text-on-surface-variant">{post.authorCollege} · {post.createdAt}</p></div></div><span className="font-label-mono text-[9px] uppercase border-2 border-outline-variant px-2 py-1 bg-dc-blue">{post.category}</span></div>{post.title && <h3 className="font-bold text-lg mb-2">{post.title}</h3>}<p className="text-sm text-on-surface-variant leading-relaxed">{post.content}</p><div className="flex items-center gap-5 mt-5 pt-4 border-t-2 border-outline-variant font-label-mono text-[10px]"><button onClick={() => toggleLikePost(post.id)} className="flex items-center gap-2"><Heart className="w-4 h-4" /> {post.likes}</button><span className="flex items-center gap-2"><MessageSquare className="w-4 h-4" /> {post.commentsCount}</span><button className="ml-auto"><Share2 className="w-4 h-4" /></button></div></article>)}</section>
    {showNewPostModal && <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-md"><div className="bg-surface border-2 border-outline-variant p-6 max-w-lg w-full shadow-[7px_7px_0_#171717] relative"><button onClick={() => setShowNewPostModal(false)} className="absolute top-3 right-3"><X className="w-5 h-5" /></button><p className="font-label-mono text-[10px] uppercase text-on-surface-variant">COMMUNITY / PUBLISH</p><h3 className="dc-display text-4xl mt-2 mb-6">YOUR UPDATE.</h3><form onSubmit={handleCreatePost} className="space-y-4"><select value={postCategory} onChange={(e) => setPostCategory(e.target.value as typeof postCategory)} className="w-full border-2 border-outline-variant bg-surface p-3 text-sm"><option>Build in Public</option><option>Questions</option><option>Projects</option><option>Hackathons</option><option>AI</option><option>Android</option><option>General</option></select><input value={postTitle} onChange={(e) => setPostTitle(e.target.value)} placeholder="Title (optional)" className="w-full border-2 border-outline-variant bg-surface p-3 text-sm" /><textarea value={postContent} onChange={(e) => setPostContent(e.target.value)} rows={5} placeholder="What are you building?" className="w-full border-2 border-outline-variant bg-surface p-3 text-sm resize-none" required /><button type="submit" className="w-full bg-primary border-2 border-outline-variant py-3 font-label-mono text-[10px] uppercase font-bold shadow-[4px_4px_0_#171717] flex items-center justify-center gap-2"><Send className="w-4 h-4" /> Publish Post</button></form></div></div>}
  </div>;
};
