import React from 'react';
import { useAuth } from '../context/AuthContext';
import { ArrowRight, CheckCircle2, Circle, Flame, Trophy, Zap } from 'lucide-react';

export const DashboardPage: React.FC = () => {
  const { user, tasks, toggleTaskCompletion, leaderboard, setActiveTab, completeOnboarding, repAnimation } = useAuth();
  if (!user) return null;
  const completedTasksCount = tasks.filter((task) => task.completed).length;
  const currentRep = user.rep;
  const currentLevel = user.level;
  const currentStreak = user.streakDays;

  return (
    <div className="space-y-8 pb-16 relative">
      {user.hasCompletedOnboarding === false && <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-md"><div className="bg-surface border-2 border-outline-variant p-8 max-w-lg w-full shadow-[7px_7px_0_#171717] space-y-6"><p className="font-label-mono text-[10px] uppercase tracking-[0.18em] text-on-surface-variant">SESSION / INITIALIZED</p><h3 className="dc-display text-5xl">WELCOME, {user.name.split(' ')[0].toUpperCase()}.</h3><p className="text-sm text-on-surface-variant leading-relaxed">Your DevCollective workspace is empty by design. Build your profile, choose a path, and start creating your own activity.</p><div className="grid grid-cols-3 border-2 border-outline-variant"><div className="p-4 border-r-2 border-outline-variant"><span className="font-label-mono text-[9px] uppercase text-on-surface-variant block">REP</span><strong className="dc-display text-2xl block mt-1">0</strong></div><div className="p-4 border-r-2 border-outline-variant"><span className="font-label-mono text-[9px] uppercase text-on-surface-variant block">LEVEL</span><strong className="dc-display text-2xl block mt-1">1</strong></div><div className="p-4"><span className="font-label-mono text-[9px] uppercase text-on-surface-variant block">STREAK</span><strong className="dc-display text-2xl block mt-1">0</strong></div></div><button onClick={() => completeOnboarding()} className="w-full bg-primary text-on-primary border-2 border-outline-variant shadow-[4px_4px_0_#171717] py-4 font-label-mono text-xs uppercase font-bold flex items-center justify-center gap-2">ENTER WORKSPACE <ArrowRight className="w-4 h-4" /></button></div></div>}
      <section className="border-b-2 border-outline-variant pb-8"><p className="font-label-mono text-[10px] uppercase tracking-[0.2em] text-on-surface-variant mb-3">WORKSPACE / DASHBOARD</p><h2 className="dc-display text-5xl sm:text-6xl">GOOD TO SEE YOU,<br /><span className="text-primary">{user.name.split(' ')[0].toUpperCase()}.</span></h2><p className="mt-4 text-sm text-on-surface-variant max-w-2xl">Everything here is driven by your activity. No tasks, achievements, projects, or rankings are preloaded.</p></section>
      <section className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[['REP', currentRep.toLocaleString(), 'TOTAL REPUTATION'], ['LEVEL', String(currentLevel), 'CURRENT LEVEL'], ['STREAK', `${currentStreak}d`, 'CURRENT STREAK'], ['TASKS', `${completedTasksCount}/${tasks.length}`, 'TASK PROGRESS']].map(([label, value, note]) => <div key={label} className="border-2 border-outline-variant bg-surface p-5 shadow-[4px_4px_0_#171717]"><span className="font-label-mono text-[10px] uppercase text-on-surface-variant block">{label}</span><span className="dc-display text-3xl mt-2 block">{value}{label === 'STREAK' && <Flame className="inline w-5 h-5 ml-1" />}</span><span className="font-label-mono text-[9px] uppercase text-on-surface-variant mt-2 block">{note}</span></div>)}</section>
      {repAnimation && <div className="border-2 border-outline-variant bg-dc-mint p-4 font-label-mono text-xs uppercase font-bold">+{repAnimation.amount} REP</div>}
      <section className="grid grid-cols-1 lg:grid-cols-[1.4fr_0.8fr] gap-6"><div className="border-2 border-outline-variant bg-surface p-6 md:p-8 shadow-[5px_5px_0_#171717]"><div className="flex items-end justify-between border-b-2 border-outline-variant pb-4 mb-6"><div><p className="font-label-mono text-[10px] uppercase text-on-surface-variant">LEARNING / LIVE</p><h3 className="dc-display text-3xl mt-1">TODAY'S TASKS</h3></div><span className="font-label-mono text-[10px]">{completedTasksCount}/{tasks.length}</span></div>{tasks.length === 0 ? <div className="border-2 border-dashed border-outline-variant p-8 text-center"><Zap className="w-6 h-6 mx-auto mb-3 text-primary" /><p className="font-label-mono text-xs uppercase font-bold">NO TASKS YET</p><p className="text-xs text-on-surface-variant mt-2">Your learning tasks will appear here when a roadmap assigns them.</p><button onClick={() => setActiveTab('roadmap')} className="mt-5 border-2 border-outline-variant bg-dc-mint px-4 py-3 font-label-mono text-[10px] uppercase font-bold shadow-[3px_3px_0_#171717]">EXPLORE ROADMAPS <ArrowRight className="inline w-3 h-3 ml-1" /></button></div> : <div className="space-y-3">{tasks.map((task) => <button key={task.id} onClick={() => toggleTaskCompletion(task.id)} className="w-full flex items-center justify-between gap-4 p-4 border-2 border-outline-variant text-left bg-surface"><span className="flex items-center gap-3 text-sm">{task.completed ? <CheckCircle2 className="w-5 h-5 text-dc-mint" /> : <Circle className="w-5 h-5" />}{task.title}</span><span className="font-label-mono text-[10px] text-primary whitespace-nowrap">+{task.repReward} REP</span></button>)}</div>}</div>
      <div className="border-2 border-outline-variant bg-surface p-6 md:p-8 shadow-[5px_5px_0_#171717]"><div className="border-b-2 border-outline-variant pb-4 mb-5"><p className="font-label-mono text-[10px] uppercase text-on-surface-variant">RANKING / LIVE</p><h3 className="dc-display text-3xl mt-1">LEADERBOARD</h3></div>{leaderboard.length === 0 ? <div className="border-2 border-dashed border-outline-variant p-6 text-center"><Trophy className="w-6 h-6 mx-auto mb-3 text-dc-yellow" /><p className="font-label-mono text-xs uppercase font-bold">NO RANKINGS YET</p><p className="text-xs text-on-surface-variant mt-2">Rankings will populate when real community activity exists.</p></div> : <div className="space-y-3">{leaderboard.slice(0, 5).map((entry) => <div key={entry.id} className="flex items-center justify-between border-b border-outline-variant/40 pb-3"><span className="font-label-mono text-xs">#{entry.rank} · {entry.name}</span><span className="font-label-mono text-xs text-primary">{entry.rep}</span></div>)}</div>}<button onClick={() => setActiveTab('leaderboard')} className="w-full mt-6 border-2 border-outline-variant py-3 font-label-mono text-[10px] uppercase font-bold">VIEW RANKINGS</button></div></section>
    </div>
  );
};
