import React from 'react';
import { useAuth } from '../context/AuthContext';
import { Marquee } from '../components/Marquee';
import { ScrollReveal } from '../components/ScrollReveal';
import { ArrowDownRight, ArrowRight, GitBranch, Layers3, Terminal, Trophy, UserCheck, Users } from 'lucide-react';

const modules = [
  { number: '01', title: 'COMMUNITY', description: 'Find builders, share progress, exchange feedback, and build with people who are on the same climb.', icon: Users, tone: 'dc-pastel-lavender', action: 'community' as const },
  { number: '02', title: 'ROADMAPS', description: 'Turn a vague career goal into a practical sequence of skills, projects, milestones, and proof of work.', icon: GitBranch, tone: 'dc-pastel-mint', action: 'roadmap' as const },
  { number: '03', title: 'MENTORS', description: 'Learn from experienced developers and get perspective that goes beyond tutorials and course checklists.', icon: UserCheck, tone: 'dc-pastel-yellow', action: 'mentors' as const },
  { number: '04', title: 'REPUTATION', description: 'Make your work visible. Contributions, consistency, mentoring, and projects all become part of your developer identity.', icon: Trophy, tone: 'dc-pastel-lavender', action: 'leaderboard' as const },
];

const marqueeItems = ['BUILD IN PUBLIC', 'LEARN BY SHIPPING', 'FIND YOUR PEOPLE', 'MENTORSHIP', 'ROADMAPS', 'REPUTATION', 'PROJECTS', 'C·FLOW READY'];

export const LandingPage: React.FC = () => {
  const { setActiveTab } = useAuth();
  return (
    <div className="dc-public min-h-screen overflow-hidden">
      <section className="relative min-h-[calc(100vh-80px)] border-b-2 border-outline-variant">
        <div className="absolute inset-0 pointer-events-none"><div className="absolute -top-32 -right-32 w-[520px] h-[520px] rounded-full bg-primary-container/35 blur-3xl" /><div className="absolute bottom-0 -left-40 w-[420px] h-[420px] rounded-full bg-secondary-container/25 blur-3xl" /></div>
        <div className="relative max-w-[1500px] mx-auto px-5 sm:px-8 lg:px-12 pt-10 sm:pt-16 lg:pt-20 pb-10">
          <div className="flex items-center justify-between gap-4 border-b-2 border-outline-variant pb-5"><span className="dc-mono text-[10px] sm:text-xs uppercase tracking-[0.18em]">DC / 01 — Developer Collective</span><span className="dc-mono text-[10px] sm:text-xs uppercase tracking-[0.18em] hidden sm:block">Build. Scale. Lead.</span></div>
          <ScrollReveal><div className="pt-12 sm:pt-16 lg:pt-20 grid lg:grid-cols-[1.35fr_0.65fr] gap-10 lg:gap-16 items-end">
            <div><p className="dc-mono text-xs sm:text-sm uppercase tracking-[0.22em] text-primary mb-6">A developer ecosystem for college builders.</p><h1 className="dc-display text-[clamp(4.4rem,11vw,10.5rem)] max-w-6xl text-on-background">Build your<br /><span className="text-primary">developer</span><br />identity.</h1></div>
            <div className="lg:pb-3"><p className="text-base sm:text-lg leading-relaxed text-on-surface-variant max-w-md mb-8">DevCollective brings community, mentorship, learning paths, projects, and reputation into one place — built for students who want to ship, not just study.</p><div className="flex flex-wrap gap-3"><button onClick={() => setActiveTab('register')} className="dc-hard-shadow-sm inline-flex items-center gap-3 px-6 py-4 bg-primary text-on-primary border-2 border-outline-variant font-bold uppercase tracking-wide">Start building <ArrowRight className="w-4 h-4" /></button><button onClick={() => setActiveTab('login')} className="inline-flex items-center gap-3 px-6 py-4 bg-surface border-2 border-outline-variant font-bold uppercase tracking-wide hover:bg-surface-container-high">Sign in</button></div></div>
          </div></ScrollReveal>
          <div className="mt-16 sm:mt-20 grid grid-cols-2 md:grid-cols-4 border-2 border-outline-variant bg-surface/70 backdrop-blur-sm">{[['01','COMMUNITY'],['02','MENTORSHIP'],['03','PROOF OF WORK'],['04','C·FLOW READY']].map(([number,label], index) => <ScrollReveal key={number} delay={index*70}><div className="p-5 sm:p-6 min-h-[105px] border-b-2 md:border-b-0 border-outline-variant"><div className="dc-mono text-[10px] text-primary mb-4">{number}</div><div className="font-bold text-sm tracking-tight">{label}</div></div></ScrollReveal>)}</div>
        </div>
      </section>

      <Marquee items={marqueeItems} />

      <section className="max-w-[1500px] mx-auto px-5 sm:px-8 lg:px-12 py-24 sm:py-32"><ScrollReveal><div className="grid lg:grid-cols-[0.3fr_1.7fr] gap-8 lg:gap-16"><div className="dc-mono text-xs uppercase tracking-[0.2em] text-primary">[ 00 / Why ]</div><div><h2 className="dc-display text-5xl sm:text-6xl lg:text-8xl max-w-5xl">The internet taught us to consume. <span className="text-primary">We are here to build.</span></h2><p className="mt-10 max-w-2xl text-lg leading-relaxed text-on-surface-variant">College is where developer habits are formed. DevCollective gives those habits a home: people to learn with, mentors to question, projects to ship, and a visible record of the work you put in.</p></div></div></ScrollReveal></section>

      <Marquee items={['SHIP SOMETHING','GET FEEDBACK','ITERATE','HELP SOMEONE','LEVEL UP','REPEAT']} reverse className="bg-secondary" />

      <section className="border-y-2 border-outline-variant bg-surface-container-lowest"><div className="max-w-[1500px] mx-auto px-5 sm:px-8 lg:px-12 py-24 sm:py-32"><ScrollReveal><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-6 mb-12"><div><p className="dc-mono text-xs uppercase tracking-[0.2em] text-primary mb-4">[ 01 / The system ]</p><h2 className="dc-display text-5xl sm:text-6xl lg:text-7xl">One ecosystem.<br /><span className="text-secondary">Many ways to grow.</span></h2></div><p className="dc-mono text-[10px] uppercase tracking-[0.15em] text-on-surface-variant max-w-xs">Every module connects back to the same goal: make your next step obvious.</p></div></ScrollReveal>
        <div className="grid md:grid-cols-2 border-t-2 border-l-2 border-outline-variant">{modules.map((module,index)=>{const Icon=module.icon;return <ScrollReveal key={module.number} delay={index*80} className="h-full"><button onClick={()=>setActiveTab(module.action)} className="group relative w-full h-full min-h-[330px] text-left border-r-2 border-b-2 border-outline-variant p-7 sm:p-9 bg-background hover:bg-surface transition-colors"><div className="flex items-start justify-between gap-5"><span className="dc-mono text-xs text-on-surface-variant">{module.number}</span><span className={`w-12 h-12 flex items-center justify-center border-2 border-outline-variant ${module.tone} dc-hard-shadow-sm`}><Icon className="w-5 h-5" /></span></div><div className="mt-16 sm:mt-20 flex items-end justify-between gap-8"><div><h3 className="dc-display text-4xl sm:text-5xl mb-4 group-hover:text-primary transition-colors">{module.title}</h3><p className="text-sm sm:text-base leading-relaxed text-on-surface-variant max-w-md">{module.description}</p></div><ArrowDownRight className="w-7 h-7 shrink-0 group-hover:translate-x-1 group-hover:translate-y-1 transition-transform" /></div></button></ScrollReveal>})}</div>
      </div></section>

      <section className="max-w-[1500px] mx-auto px-5 sm:px-8 lg:px-12 py-24 sm:py-32"><ScrollReveal><div className="border-2 border-outline-variant bg-primary-container p-7 sm:p-10 lg:p-14 dc-hard-shadow"><div className="grid lg:grid-cols-[0.6fr_1.4fr] gap-12 items-start"><div><p className="dc-mono text-xs uppercase tracking-[0.2em] text-on-primary mb-5">[ 02 / The loop ]</p><h2 className="dc-display text-5xl sm:text-6xl lg:text-7xl text-on-primary">Learn.<br />Build.<br />Share.</h2></div><div className="grid sm:grid-cols-3 border-2 border-outline-variant">{[{n:'01',title:'LEARN',text:'Use structured roadmaps and mentors to understand what matters next.'},{n:'02',title:'BUILD',text:'Turn knowledge into projects, contributions, and real proof of work.'},{n:'03',title:'SHARE',text:'Get feedback, help peers, earn reputation, and keep the loop moving.'}].map((step,index)=><div key={step.n} className={`p-6 sm:p-7 bg-background border-outline-variant ${index<2?'border-b-2 sm:border-b-0 sm:border-r-2':''}`}><span className="dc-mono text-[10px] text-primary">{step.n}</span><h3 className="dc-display text-3xl mt-12 mb-3">{step.title}</h3><p className="text-sm text-on-surface-variant leading-relaxed">{step.text}</p></div>)}</div></div></div></ScrollReveal></section>

      <section className="border-y-2 border-outline-variant bg-secondary-container"><div className="max-w-[1500px] mx-auto px-5 sm:px-8 lg:px-12 py-20 sm:py-24"><ScrollReveal><div className="grid lg:grid-cols-[1fr_auto] gap-10 items-center"><div><div className="flex items-center gap-3 dc-mono text-xs uppercase tracking-[0.2em] mb-5"><Terminal className="w-4 h-4" />Next module / C·FLOW</div><h2 className="dc-display text-5xl sm:text-6xl lg:text-8xl text-on-secondary max-w-5xl">Visualize the code you build.</h2><p className="mt-6 max-w-2xl text-base sm:text-lg leading-relaxed text-on-secondary/75">DevCollective is being shaped to become the home for C·FLOW too — taking the same build-first mindset from community and roadmaps into interactive code visualization.</p></div><div className="border-2 border-outline-variant bg-background p-6 sm:p-8 dc-hard-shadow-sm min-w-[220px]"><Layers3 className="w-8 h-8 mb-8 text-secondary" /><div className="dc-mono text-[10px] uppercase tracking-[0.16em] text-on-surface-variant">Integration status</div><div className="dc-display text-4xl mt-2">IN BUILD</div></div></div></ScrollReveal></div></section>

      <section className="max-w-[1500px] mx-auto px-5 sm:px-8 lg:px-12 py-24 sm:py-36"><ScrollReveal><div className="text-center"><p className="dc-mono text-xs uppercase tracking-[0.22em] text-primary mb-6">[ 03 / Your turn ]</p><h2 className="dc-display text-[clamp(4rem,10vw,9rem)]">Stop waiting.<br /><span className="text-primary">Start shipping.</span></h2><p className="max-w-xl mx-auto mt-8 text-lg text-on-surface-variant leading-relaxed">Your next project, mentor, roadmap, and collaborator are closer than you think.</p><div className="mt-9 flex justify-center gap-3 flex-wrap"><button onClick={()=>setActiveTab('register')} className="dc-hard-shadow inline-flex items-center gap-3 px-8 py-4 bg-primary text-on-primary border-2 border-outline-variant font-bold uppercase tracking-wide">Join DevCollective <ArrowRight className="w-4 h-4" /></button><button onClick={()=>setActiveTab('roadmap')} className="inline-flex items-center gap-3 px-8 py-4 bg-surface border-2 border-outline-variant font-bold uppercase tracking-wide">Explore roadmap</button></div></div></ScrollReveal></section>
      <footer className="border-t-2 border-outline-variant px-5 sm:px-8 lg:px-12 py-8 max-w-[1500px] mx-auto flex flex-col sm:flex-row gap-4 justify-between dc-mono text-[10px] uppercase tracking-[0.15em] text-on-surface-variant"><span>DEV_COLLECTIVE / 2026</span><span>BUILD. SCALE. LEAD.</span></footer>
    </div>
  );
};
