import React, { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { LEVEL_0_MODULES, LEVEL_0_SUBTITLE, LEVEL_0_TITLE, Level0Module, Level0Submodule } from '../data/level0';
import { Level0Activity } from '../components/Level0Activity';
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, ChevronDown, Circle, Clock, Code2, Cpu, ExternalLink, GraduationCap, GitBranch, Layers, Network, Play, ShieldCheck, Sparkles, Target, Terminal, X } from 'lucide-react';

interface ModuleProgress { verifiedSubmodules: string[]; completedAt?: string; }
type ProgressMap = Record<string, ModuleProgress>;
const ICONS: Record<string, React.ReactNode> = { layers: <Layers className="h-5 w-5" />, 'git-branch': <GitBranch className="h-5 w-5" />, network: <Network className="h-5 w-5" />, 'code-2': <Code2 className="h-5 w-5" />, 'graduation-cap': <GraduationCap className="h-5 w-5" />, cpu: <Cpu className="h-5 w-5" /> };
const storageKey = (userId: string) => `devcollective_level_progress_${userId}`;
function youtubeEmbedUrl(resourceUrl: string, embedUrl?: string) { if (embedUrl) return embedUrl; try { const url = new URL(resourceUrl); if (url.hostname.includes('youtu.be')) return `https://www.youtube.com/embed/${url.pathname.replace('/', '')}`; if (url.hostname.includes('youtube.com')) { const id = url.searchParams.get('v'); if (id) return `https://www.youtube.com/embed/${id}`; } } catch { return undefined; } return undefined; }

export const Level0Page: React.FC = () => {
  const { user } = useAuth();
  const [selectedModuleId, setSelectedModuleId] = useState(LEVEL_0_MODULES[0]?.id ?? '');
  const [selectedSubmoduleId, setSelectedSubmoduleId] = useState(LEVEL_0_MODULES[0]?.submodules[0]?.id ?? '');
  const [progress, setProgress] = useState<ProgressMap>({});
  const [expandedModuleId, setExpandedModuleId] = useState<string | null>(LEVEL_0_MODULES[0]?.id ?? null);
  const [videoResourceId, setVideoResourceId] = useState<string | null>(null);
  const [verifying, setVerifying] = useState(false);
  const [verificationError, setVerificationError] = useState<string | null>(null);

  useEffect(() => { if (!user) return; try { const raw = localStorage.getItem(storageKey(user.id)); if (raw) setProgress(JSON.parse(raw)); } catch (error) { console.error('Failed to load Level 0 progress', error); } }, [user]);
  const selectedModule = useMemo(() => LEVEL_0_MODULES.find((module) => module.id === selectedModuleId) ?? LEVEL_0_MODULES[0], [selectedModuleId]);
  const selectedSubmodule = useMemo(() => selectedModule?.submodules.find((submodule) => submodule.id === selectedSubmoduleId) ?? selectedModule?.submodules[0], [selectedModule, selectedSubmoduleId]);
  const totalSubmodules = LEVEL_0_MODULES.reduce((sum, module) => sum + module.submodules.length, 0);
  const verifiedSubmodules = LEVEL_0_MODULES.reduce((sum, module) => sum + (progress[module.id]?.verifiedSubmodules.length ?? 0), 0);
  const completedModules = LEVEL_0_MODULES.reduce((sum, module) => sum + (progress[module.id]?.completedAt ? 1 : 0), 0);
  const overallPercent = totalSubmodules ? Math.round((verifiedSubmodules / totalSubmodules) * 100) : 0;
  const levelComplete = completedModules === LEVEL_0_MODULES.length;
  const selectModule = (module: Level0Module) => { setSelectedModuleId(module.id); setSelectedSubmoduleId(module.submodules[0]?.id ?? ''); setExpandedModuleId(module.id); setVideoResourceId(null); setVerificationError(null); };
  const selectSubmodule = (module: Level0Module, submodule: Level0Submodule) => { setSelectedModuleId(module.id); setSelectedSubmoduleId(submodule.id); setExpandedModuleId(module.id); setVideoResourceId(null); setVerificationError(null); };
  const saveLocalVerification = (module: Level0Module, submodule: Level0Submodule) => { if (!user) return; const current = progress[module.id] ?? { verifiedSubmodules: [] }; if (current.verifiedSubmodules.includes(submodule.id)) return; const verified = [...current.verifiedSubmodules, submodule.id]; const next: ProgressMap = { ...progress, [module.id]: { verifiedSubmodules: verified, completedAt: verified.length === module.submodules.length ? new Date().toISOString() : current.completedAt } }; setProgress(next); localStorage.setItem(storageKey(user.id), JSON.stringify(next)); };
  const verifySubmodule = async (module: Level0Module, submodule: Level0Submodule) => { if (!user || verifying) return; setVerificationError(null); setVerifying(true); try { if (submodule.id === 'how-software-comes-together') { const response = await fetch(`/api/learning/level-0/submodules/${encodeURIComponent(submodule.id)}/verify`, { method: 'POST', headers: { 'Content-Type': 'application/json' } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || `Verification failed (${response.status}).`); } saveLocalVerification(module, submodule); } catch (error: any) { console.error('Level 0 verification failed:', error); setVerificationError(error?.message || 'Could not verify this sub-module on the server.'); } finally { setVerifying(false); } };
  const moduleProgress = selectedModule ? progress[selectedModule.id]?.verifiedSubmodules.length ?? 0 : 0;
  const selectedVerified = Boolean(selectedModule && selectedSubmodule && progress[selectedModule.id]?.verifiedSubmodules.includes(selectedSubmodule.id));

  return <div className="dc-level0 min-h-full pb-12 text-on-background"><div className="mx-auto max-w-[1500px] space-y-5">
    <div className="flex items-center gap-2 px-1 pt-1 font-label-mono text-[10px] uppercase tracking-[0.08em] text-outline"><span className="text-primary">●</span> Learning <span>/</span> <span className="text-on-surface">Level 0</span></div>
    <header className="dc-level0-hero border-2 border-outline-variant bg-surface-container shadow-[7px_7px_0_var(--outline)]"><div className="dc-level0-hero-copy"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 font-label-mono text-[10px] font-bold uppercase text-primary"><ShieldCheck className="h-3.5 w-3.5" /> Mandatory foundation</div><h1 className="dc-level0-title"><span className="dc-level0-title-accent">Level 0</span><span> — {LEVEL_0_TITLE}</span></h1><p className="dc-level0-subtitle">{LEVEL_0_SUBTITLE}. Build the common CSE foundation before specializing.</p><div className="mt-5 flex flex-wrap gap-2"><span className="dc-level0-chip"><Layers className="h-3.5 w-3.5" /> {LEVEL_0_MODULES.length} modules</span><span className="dc-level0-chip"><BookOpen className="h-3.5 w-3.5" /> {totalSubmodules} sub-modules</span><span className="dc-level0-chip"><ShieldCheck className="h-3.5 w-3.5" /> mandatory</span><span className="dc-level0-chip"><Clock className="h-3.5 w-3.5" /> foundation path</span></div></div><div className="dc-level0-progress-card"><div className="flex items-center justify-between gap-4"><span className="font-label-mono text-[10px] uppercase tracking-wider text-outline">Your progress</span><span className="font-label-mono text-[10px] uppercase text-outline">{verifiedSubmodules}/{totalSubmodules}</span></div><div className="dc-level0-progress-ring" style={{ '--progress': `${overallPercent * 3.6}deg` } as React.CSSProperties}><span>{overallPercent}%</span></div><div className="grid grid-cols-2 gap-2"><div><span>Modules</span><strong>{completedModules}/{LEVEL_0_MODULES.length}</strong></div><div><span>Sub-modules</span><strong>{verifiedSubmodules}/{totalSubmodules}</strong></div></div></div></header>
    <div className="grid grid-cols-1 gap-4 xl:grid-cols-[350px_minmax(0,1fr)]">
      <aside className="dc-level0-modules border-2 border-outline-variant bg-surface-container"><div className="flex items-center justify-between border-b border-outline-variant px-4 py-3"><div><div className="font-label-mono text-[10px] uppercase text-outline">Modules ({LEVEL_0_MODULES.length})</div><div className="mt-1 text-sm font-black">Foundation Path</div></div><Target className="h-5 w-5 text-primary" /></div><div className="space-y-1 p-2">{LEVEL_0_MODULES.map((module) => { const count = progress[module.id]?.verifiedSubmodules.length ?? 0; const active = selectedModule?.id === module.id; const expanded = expandedModuleId === module.id; const complete = Boolean(progress[module.id]?.completedAt); return <div key={module.id}><button type="button" onClick={() => { selectModule(module); if (expanded) setExpandedModuleId(null); }} className={`dc-level0-module ${active ? 'is-active' : ''}`}><span className="dc-level0-module-icon">{complete ? <CheckCircle2 className="h-5 w-5" /> : ICONS[module.icon]}</span><span className="min-w-0 flex-1 text-left"><strong>{module.order}. {module.title}</strong><small>{count}/{module.submodules.length} completed</small></span><ChevronDown className={`h-4 w-4 shrink-0 transition-transform ${expanded ? 'rotate-180' : ''}`} /></button>{expanded && <div className="space-y-1 px-2 pb-2 pt-1">{module.submodules.map((submodule, index) => { const verified = progress[module.id]?.verifiedSubmodules.includes(submodule.id); const activeSub = selectedSubmodule?.id === submodule.id; return <button type="button" key={submodule.id} onClick={() => selectSubmodule(module, submodule)} className={`dc-level0-submodule ${activeSub ? 'is-active' : ''}`}>{verified ? <CheckCircle2 className="h-4 w-4 text-tertiary" /> : <Circle className="h-4 w-4 text-outline" />}<span>{index + 1}. {submodule.title}</span><small>{submodule.estimatedMinutes}m</small></button>; })}</div>}</div>; })}</div></aside>
      {selectedModule && selectedSubmodule && <main className="min-w-0 border-2 border-outline-variant bg-surface-container"><section className="dc-level0-module-header"><div><div className="mb-2 flex flex-wrap items-center gap-2"><span className="dc-level0-label bg-tertiary/10 text-tertiary">Module {selectedModule.order}</span><span className="dc-level0-label">~ {selectedModule.estimatedMinutes} min</span></div><h2>{selectedModule.title}</h2><p>{selectedModule.description}</p></div><div className="dc-level0-module-count"><strong>{moduleProgress}/{selectedModule.submodules.length}</strong><span>completed</span></div></section>
        <section className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_minmax(320px,1.15fr)]"><div className="border-b border-outline-variant p-4 lg:border-b-0 lg:border-r"><div className="mb-3 font-label-mono text-[10px] uppercase text-outline">Sub-modules ({selectedModule.submodules.length})</div><div className="space-y-1.5">{selectedModule.submodules.map((submodule, index) => { const active = submodule.id === selectedSubmodule.id; const verified = progress[selectedModule.id]?.verifiedSubmodules.includes(submodule.id); return <button type="button" key={submodule.id} onClick={() => selectSubmodule(selectedModule, submodule)} className={`dc-level0-lesson ${active ? 'is-active' : ''}`}><span className="dc-level0-lesson-number">{verified ? <Check className="h-4 w-4" /> : `0${index + 1}`}</span><span className="min-w-0 flex-1 text-left"><strong>{submodule.title}</strong><small><Clock className="h-3 w-3" /> {submodule.estimatedMinutes} min</small></span><ArrowRight className="h-4 w-4" /></button>; })}</div></div>
          <div className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2 font-label-mono text-[10px] uppercase text-primary">{selectedSubmodule.kind === 'interactive' && <Sparkles className="h-3.5 w-3.5" />}{selectedSubmodule.kind === 'practical' && <Terminal className="h-3.5 w-3.5" />}{selectedSubmodule.kind === 'assessment' && <ShieldCheck className="h-3.5 w-3.5" />}{selectedSubmodule.kind}</div><h3 className="dc-level0-lesson-title">{selectedSubmodule.title}</h3><p className="mt-1 text-sm leading-6 text-on-surface-variant">{selectedSubmodule.description}</p></div>{selectedVerified && <span className="dc-level0-verified"><Check className="h-4 w-4" /> Verified</span>}</div>
            {selectedSubmodule.id === 'how-software-comes-together' ? <Level0Activity verified={selectedVerified} verifying={verifying} onVerify={() => verifySubmodule(selectedModule, selectedSubmodule)} /> : <><div className="mt-5 space-y-2">{selectedSubmodule.content.map((paragraph, index) => <div key={index} className="dc-level0-content-row"><span>{index + 1}</span><p>{paragraph}</p></div>)}</div>{selectedSubmodule.resources?.length ? <div className="mt-5 border-2 border-outline-variant bg-surface"><div className="flex items-center gap-2 border-b border-outline-variant px-4 py-3"><BookOpen className="h-4 w-4 text-secondary" /><span className="text-xs font-black">Best Free Resources</span></div><div className="space-y-2 p-3">{selectedSubmodule.resources.map((resource) => { const embed = resource.type === 'video' ? youtubeEmbedUrl(resource.url, resource.embedUrl) : undefined; return <div key={resource.id} className="border border-outline-variant bg-surface-container-low p-3">{embed && <div className="mb-3 aspect-video overflow-hidden bg-black"><iframe src={embed} title={resource.title} className="h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /></div>}<div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="font-label-mono text-[9px] uppercase text-outline">{resource.provider ?? resource.type}</div><div className="mt-1 text-sm font-bold">{resource.title}</div><p className="mt-1 text-xs text-on-surface-variant">{resource.description}</p></div>{!embed && <a href={resource.url} target="_blank" rel="noreferrer" className="shrink-0 border border-outline-variant bg-surface px-3 py-2 text-xs font-bold">Open <ExternalLink className="ml-1 inline h-3 w-3" /></a>}{embed && resource.type === 'video' && <button type="button" onClick={() => setVideoResourceId(resource.id)} className="shrink-0 border border-outline-variant bg-surface px-3 py-2 text-xs font-bold"><Play className="mr-1 inline h-3 w-3" /> View</button>}</div></div>; })}</div></div> : null}<div className="mt-5 flex flex-col gap-3 border-2 border-primary/20 bg-primary/5 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-xs font-black">Verification checkpoint</div><p className="mt-1 text-xs text-on-surface-variant">Finish this sub-module, then verify the checkpoint.</p></div><button type="button" onClick={() => void verifySubmodule(selectedModule, selectedSubmodule)} disabled={selectedVerified || verifying} className="shrink-0 border-2 border-outline bg-primary px-4 py-2.5 text-xs font-black uppercase disabled:cursor-default disabled:opacity-50">{selectedVerified ? 'Verified' : verifying ? 'Verifying…' : 'Mark complete'}</button></div></>}
            {verificationError && <div className="mt-4 border-2 border-red-400/40 bg-red-400/10 px-4 py-3 text-xs font-bold text-red-700 dark:text-red-300">{verificationError}</div>}
            <div className="mt-4 flex items-center justify-between gap-3"><button type="button" disabled={selectedModule.submodules.findIndex((item) => item.id === selectedSubmodule.id) <= 0} onClick={() => { const i = selectedModule.submodules.findIndex((item) => item.id === selectedSubmodule.id); if (i > 0) selectSubmodule(selectedModule, selectedModule.submodules[i - 1]); }} className="inline-flex items-center gap-2 border border-outline-variant px-3 py-2 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4" /> Previous</button><button type="button" disabled={selectedModule.submodules.findIndex((item) => item.id === selectedSubmodule.id) >= selectedModule.submodules.length - 1} onClick={() => { const i = selectedModule.submodules.findIndex((item) => item.id === selectedSubmodule.id); if (i < selectedModule.submodules.length - 1) selectSubmodule(selectedModule, selectedModule.submodules[i + 1]); }} className="inline-flex items-center gap-2 border-2 border-outline bg-surface px-3 py-2 text-xs font-bold disabled:opacity-30">Next <ArrowRight className="h-4 w-4" /></button></div>
          </div></section></main>}
    </div>
    <div className="grid grid-cols-1 gap-3 md:grid-cols-3"><div className="dc-level0-stat"><span>Module REP</span><strong>+{selectedModule?.repReward ?? 0}</strong><small>Earned on module completion.</small></div><div className="dc-level0-stat"><span>Sub-module REP</span><strong>+{selectedSubmodule?.repReward ?? 0}</strong><small>Curriculum reward metadata.</small></div><div className="dc-level0-stat"><span>Level state</span><strong className={levelComplete ? 'text-tertiary' : 'text-primary'}>{levelComplete ? 'OPEN' : 'LOCKED'}</strong><small>{levelComplete ? 'Specialization unlocked.' : 'Complete all Level 0 modules first.'}</small></div></div>
  </div>{videoResourceId && selectedSubmodule && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" onClick={() => setVideoResourceId(null)}><div className="w-full max-w-4xl border-2 border-outline bg-surface-container" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b border-outline-variant p-3"><span className="text-sm font-black">Video Resource</span><button type="button" onClick={() => setVideoResourceId(null)}><X className="h-5 w-5" /></button></div><div className="aspect-video bg-black">{(() => { const resource = selectedSubmodule.resources?.find((item) => item.id === videoResourceId); const embed = resource ? youtubeEmbedUrl(resource.url, resource.embedUrl) : undefined; return embed ? <iframe src={embed} title={resource.title} className="h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /> : null; })()}</div></div></div>}</div>;
};
