import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { Mentor } from '../types';
import { Calendar, MessageSquare, Search, X } from 'lucide-react';
import { openMessagingForUser } from '../components/MessagingOverlay';

export const MentorDirectoryPage: React.FC = () => {
  const { mentors, user } = useAuth();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedRole, setSelectedRole] = useState('ALL');
  const [activeMentor, setActiveMentor] = useState<Mentor | null>(null);
  const [bookingConfirmed, setBookingConfirmed] = useState(false);
  const filtered = mentors.filter((mentor) => {
    const roleMatch = selectedRole === 'ALL' || mentor.roleType === selectedRole;
    const query = searchQuery.toLowerCase();
    return roleMatch && (!query || mentor.name.toLowerCase().includes(query) || mentor.college.toLowerCase().includes(query) || mentor.skills.some((skill) => skill.toLowerCase().includes(query)));
  });
  const book = () => { setBookingConfirmed(true); setTimeout(() => { setBookingConfirmed(false); setActiveMentor(null); }, 1200); };

  return <div className="space-y-8 pb-16">
    <section className="flex flex-col lg:flex-row lg:items-end justify-between gap-6 border-b-2 border-outline-variant pb-7"><div><p className="font-label-mono text-[10px] uppercase tracking-[0.18em] text-on-surface-variant">MENTORS / LIVE DATABASE</p><h2 className="dc-display text-5xl sm:text-6xl mt-2">MENTORS.</h2><p className="mt-4 text-sm text-on-surface-variant max-w-xl">Only profiles whose role is marked as <strong>mentor</strong> in the DevCollective database appear here.</p></div><div className="relative w-full lg:w-80"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-on-surface-variant" /><input value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="Search real mentors..." className="w-full border-2 border-outline-variant bg-surface py-3 pl-10 pr-4 text-xs font-label-mono" /></div></section>
    <section className="border-2 border-outline-variant bg-surface p-5 shadow-[4px_4px_0_#171717]"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><p className="font-label-mono text-[10px] uppercase text-on-surface-variant">YOUR ACCESS</p><p className="font-label-mono text-sm uppercase mt-1">LEVEL {user?.level ?? 1} · {user?.rep ?? 0} REP</p></div><div className="font-label-mono text-[10px] uppercase text-on-surface-variant">Beta messaging · all authenticated users</div></div></section>
    <div className="flex flex-wrap gap-2">{['ALL', 'SENIOR', 'FACULTY'].map((role) => <button key={role} onClick={() => setSelectedRole(role)} className={`border-2 border-outline-variant px-3 py-2 font-label-mono text-[10px] uppercase font-bold ${selectedRole === role ? 'bg-primary text-on-primary shadow-[3px_3px_0_#171717]' : 'bg-surface'}`}>{role}</button>)}</div>
    {filtered.length === 0 ? <section className="border-2 border-dashed border-outline-variant bg-surface p-12 text-center"><p className="dc-display text-4xl">NO MENTORS YET.</p><p className="text-sm text-on-surface-variant mt-3">There are currently no mentor profiles available in the database.</p></section> : <section className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">{filtered.map((mentor) => <article key={mentor.id} className="border-2 border-outline-variant bg-surface p-6 shadow-[5px_5px_0_#171717]"><div className="flex items-start justify-between gap-3 mb-5"><div className="flex items-center gap-3">{mentor.avatar ? <img src={mentor.avatar} alt={mentor.name} className="w-14 h-14 border-2 border-outline-variant object-cover" /> : <div className="w-14 h-14 border-2 border-outline-variant bg-dc-yellow flex items-center justify-center font-bold">{mentor.name.slice(0,1)}</div>}<div><h3 className="font-bold text-lg">{mentor.name}</h3><p className="font-label-mono text-[9px] uppercase text-on-surface-variant">{mentor.title}</p></div></div><span className="border-2 border-outline-variant bg-dc-blue px-2 py-1 font-label-mono text-[9px]">{mentor.roleType}</span></div><p className="text-xs text-on-surface-variant leading-relaxed min-h-10">{mentor.bio || 'No bio provided.'}</p><p className="font-label-mono text-[10px] uppercase text-on-surface-variant mt-4">{mentor.college || 'College not provided'}</p><div className="flex flex-wrap gap-2 mt-4">{mentor.skills.length ? mentor.skills.map((skill) => <span key={skill} className="bg-dc-mint border-2 border-outline-variant px-2 py-1 font-label-mono text-[9px] uppercase">{skill}</span>) : <span className="font-label-mono text-[9px] text-on-surface-variant">NO SKILLS LISTED</span>}</div><div className="grid grid-cols-2 gap-3 border-y-2 border-outline-variant my-5 py-3"><div><span className="font-label-mono text-[9px] uppercase text-on-surface-variant block">LEVEL</span><strong>{mentor.level}</strong></div><div><span className="font-label-mono text-[9px] uppercase text-on-surface-variant block">REP</span><strong>{mentor.rep}</strong></div></div><div className="grid grid-cols-2 gap-2"><button onClick={() => setActiveMentor(mentor)} className="border-2 border-outline-variant bg-primary text-on-primary py-3 font-label-mono text-[10px] uppercase font-bold flex items-center justify-center gap-2"><Calendar className="w-4 h-4" /> Book</button><button onClick={() => openMessagingForUser(mentor.id)} className="border-2 border-outline-variant bg-dc-blue py-3 font-label-mono text-[10px] uppercase font-bold flex items-center justify-center gap-2 hover:bg-dc-lavender"><MessageSquare className="w-4 h-4" /> Message</button></div></article>)}</section>}
    {activeMentor && <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-md"><div className="bg-surface border-2 border-outline-variant p-6 max-w-md w-full shadow-[7px_7px_0_#171717] relative"><button onClick={() => setActiveMentor(null)} className="absolute top-3 right-3"><X className="w-5 h-5" /></button><p className="font-label-mono text-[10px] uppercase text-on-surface-variant">MENTOR / SESSION</p><h3 className="dc-display text-4xl mt-2">{activeMentor.name}.</h3><p className="text-sm text-on-surface-variant mt-3">{activeMentor.availability}</p><p className="font-label-mono text-[10px] uppercase mt-5 mb-2">SESSION TOPIC</p><input placeholder="What do you want help with?" className="w-full border-2 border-outline-variant bg-surface p-3 text-sm" /><button onClick={book} className="w-full mt-5 border-2 border-outline-variant bg-dc-mint py-3 font-label-mono text-[10px] uppercase font-bold shadow-[4px_4px_0_#171717]">{bookingConfirmed ? 'REQUEST SENT' : 'REQUEST SESSION'}</button></div></div>}
  </div>;
};
