import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { Search, Bell, Shield, LogOut, User, Terminal, Menu, X } from 'lucide-react';
import { ThemeToggle } from './ThemeToggle';

export const Navbar: React.FC = () => {
  const { user, activeTab, setActiveTab, logout, setShowOAuthModal } = useAuth();
  const [showNotifications, setShowNotifications] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const isStandalone = ['landing', 'login', 'register'].includes(activeTab);
  return (
    <header className="sticky top-0 z-40 h-[74px] border-b-2 border-outline-variant bg-background/90 backdrop-blur-xl flex items-center justify-between px-4 sm:px-6 lg:px-10">
      <div className="flex items-center gap-3 min-w-0">
        <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="md:hidden p-2 border-2 border-outline-variant bg-surface hover:bg-surface-container-high" aria-label="Toggle menu">{mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}</button>
        {isStandalone ? <button onClick={() => setActiveTab(user ? 'dashboard' : 'landing')} className="flex items-center gap-3"><span className="w-9 h-9 border-2 border-outline-variant bg-primary flex items-center justify-center text-on-primary"><Terminal className="w-5 h-5" /></span><span className="font-headline-md text-xl sm:text-2xl font-bold tracking-tight hidden sm:block">DEV_COLLECTIVE</span></button> : <div className="flex items-center gap-3 w-full max-w-md border-2 border-outline-variant bg-surface px-4 py-2.5"><Search className="w-4 h-4 text-on-surface-variant" /><input type="text" placeholder="Search projects, mentors, roadmaps..." className="bg-transparent border-none outline-none text-xs sm:text-sm w-full text-on-surface placeholder:text-on-surface-variant" /></div>}
      </div>
      <div className="flex items-center gap-2 sm:gap-3"><ThemeToggle /><button onClick={() => setShowOAuthModal(true)} className="hidden sm:flex items-center gap-2 px-3 py-1.5 bg-surface-container border border-outline-variant hover:border-primary rounded-full text-xs font-label-mono text-primary" title="Configure Google and GitHub OAuth"><Shield className="w-3.5 h-3.5" /><span>OAuth Keys</span></button><div className="relative"><button onClick={() => setShowNotifications(!showNotifications)} className="relative text-on-surface-variant hover:text-primary p-2 rounded-full"><Bell className="w-5 h-5" /><span className="absolute top-1 right-1 w-2 h-2 bg-error rounded-full" /></button>{showNotifications && <div className="absolute right-0 mt-2 w-80 bg-surface-container border-2 border-outline-variant rounded-2xl p-4 shadow-2xl z-50"><div className="flex justify-between items-center mb-3 pb-2 border-b border-outline-variant"><span className="font-label-mono text-xs uppercase font-bold text-primary">Notifications</span><span className="text-[10px] text-outline">3 New</span></div><div className="space-y-3 text-xs"><div className="p-2.5 bg-surface-container-low rounded-xl border border-outline-variant/30"><p className="font-bold text-white mb-0.5">Level 18 Unlocked!</p><p className="text-on-surface-variant text-[11px]">You earned +50 REP for completing Neural Networks introduction.</p></div><div className="p-2.5 bg-surface-container-low rounded-xl border border-outline-variant/30"><p className="font-bold text-white mb-0.5">Mentor Feedback</p><p className="text-on-surface-variant text-[11px]">Rahul Sharma reviewed your PyTorch project repository.</p></div></div></div>}</div>{user ? <div className="flex items-center gap-2"><button onClick={() => setActiveTab('profile')} className="flex items-center gap-2 bg-surface border-2 border-outline-variant p-1 pr-2 sm:pr-3 hover:border-primary"><img src={user.avatar} alt={user.name} className="w-8 h-8 object-cover border border-outline-variant" /><span className="dc-mono text-[9px] text-primary hidden sm:block">{user.rep.toLocaleString()} REP</span></button><button onClick={logout} title="Logout" className="p-2 border-2 border-transparent hover:border-error hover:text-error text-on-surface-variant"><LogOut className="w-4 h-4" /></button></div> : <div className="flex items-center gap-1 sm:gap-2"><button onClick={() => setActiveTab('login')} className="dc-mono text-[10px] uppercase px-3 py-2 text-on-surface-variant hover:text-primary">Login</button><button onClick={() => setActiveTab('register')} className="dc-mono text-[10px] uppercase px-4 py-2 bg-primary text-on-primary border-2 border-outline-variant">Register</button></div>}</div>
      {mobileMenuOpen && <div className="md:hidden fixed top-[74px] left-0 right-0 bg-background border-b-2 border-outline-variant p-4 shadow-[0_6px_0_var(--outline-variant)] z-50"><div className="dc-mono text-[9px] uppercase tracking-[0.16em] text-on-surface-variant mb-3">Navigation / 00</div><div className="grid grid-cols-2 gap-2">{[['dashboard','Dashboard'],['community','Community'],['roadmap','Roadmaps'],['leaderboard','Leaderboard'],['mentors','Mentors'],['profile','Profile'],['admin','Admin Terminal']].map(([id,label])=><button key={id} onClick={()=>{setActiveTab(id as any);setMobileMenuOpen(false)}} className="p-3 text-left bg-surface border-2 border-outline-variant dc-mono text-[10px] uppercase hover:border-primary">{label}</button>)}</div><div className="mt-3 p-3 border-2 border-outline-variant bg-secondary-container text-on-secondary dc-mono text-[9px] uppercase">C·FLOW / Integration in build</div></div>}
    </header>
  );
};
